wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.9
    start_time: 1639418498
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 19
      4: 3.9.9
      5: 0.12.7
      8:
      - 3
      - 5
    visualize:
      my_histogram:
        panel_config:
          fieldSettings:
            value: pixel_val
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Prediction Score Distribution
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: my_histogram_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
